Merging the news data and the yfinance data into one dataset for testing training and visualizing

In [11]:
import pandas as pd

news_data = pd.read_csv('data/news/cleaned/all_clean.csv')

news_data.head()

     adj_date                                      clean_summary
0  2020-07-20  jim cramer better way invest covid19 vaccine g...
1  2020-07-20  cramers lightning round would teradyne mad mon...
2  2020-07-20  cramers week ahead big week earnings even bigg...
3  2020-07-20  iq capital ceo keith bliss say tech healthcare...
4  2020-07-17  wall street delivered kind pullback ive waitin...

In [8]:
yfinance_data = pd.read_csv('data/stock/yfinance_data_cleaned.csv')
#renaming the date column to match for merging
yfinance_data = yfinance_data.rename(columns={'Date': 'adj_date'})
# sort by date ascending
yfinance_data = yfinance_data.sort_values(by='adj_date', ascending=True)
yfinance_data.head()

   Volume_^GSPC  pct_change  Target    adj_date
0    3407680000   -0.003230       0  2017-12-19
1    3246230000   -0.000828       1  2017-12-20
2    3293130000    0.001986       0  2017-12-21
3    2401030000   -0.000458       0  2017-12-22
4    1970660000   -0.001058       1  2017-12-26

In [13]:
# Combining datasets based on time outer join so that it keeps all data from both datasets
merged_data = pd.merge(news_data, yfinance_data, on='adj_date', how='outer')
merged_data.to_csv('data/merged_data.csv', index=False)
merged_data.head()

,adj_date,clean_summary,Volume_^GSPC,pct_change,Target
0,2017-12-18,france save marquis de sade 120 day sodom auction,NaN,NaN,NaN
1,2017-12-18,business live bitcoin bubble warning grow loud...,NaN,NaN,NaN
2,2017-12-18,eu investigates ikea dutch deal reduce tax bil...,NaN,NaN,NaN
3,2017-12-18,hermes delivery driver diary show flipside chr...,NaN,NaN,NaN
4,2017-12-18,uk manufacturing order book near threedecade h...,NaN,NaN,NaN