Merging the news data and the yfinance data into one dataset for testing training and visualizing

In [1]:
import pandas as pd

news_data = pd.read_csv('data/news/cleaned/all_clean.csv')


news_data.head()

                  date                                    cleaned_summary
0  2020-07-17 19:51:00  jim cramer better way invest covid19 vaccine g...
1  2020-07-17 19:33:00  cramers lightning round would teradyne mad mon...
2  2020-07-17 19:25:00  cramers week ahead big week earnings even bigg...
3  2020-07-17 16:24:00  iq capital ceo keith bliss say tech healthcare...
4  2020-07-16 19:36:00  wall street delivered kind pullback ive waitin...

In [6]:
yfinance_data = pd.read_csv('data/stock/yfinance_data_cleaned.csv')
#renaming the date column to match for merging
yfinance_data = yfinance_data.rename(columns={'Date': 'date'})
# sort by date ascending
yfinance_data = yfinance_data.sort_values(by='date', ascending=True)
yfinance_data.head()

   Volume_^GSPC  pct_change  Target        date
0    3727770000    0.005363       0  2017-12-18
1    3407680000   -0.003230       0  2017-12-19
2    3246230000   -0.000828       1  2017-12-20
3    3293130000    0.001986       0  2017-12-21
4    2401030000   -0.000458       0  2017-12-22

In [4]:
# Combining datasets based on time outer join so that it keeps all data from both datasets
merged_data = pd.merge(news_data, yfinance_data, on='date', how='outer')
merged_data.head()

,date,cleaned_summary,Volume_^GSPC,pct_change,Target
0,2017-12-17 00:00:00,peter preston press broadcasting paul dacre pa...,NaN,NaN,NaN
1,2017-12-17 00:00:00,business could prosper under corbyn government,NaN,NaN,NaN
2,2017-12-17 00:00:00,youngest staff given uk workplace pension qual...,NaN,NaN,NaN
3,2017-12-17 00:00:00,grogonomics year company job 2018 wage,NaN,NaN,NaN
4,2017-12-17 00:00:00,butcher carve niche uk shopper opt indie store,NaN,NaN,NaN